version: '3.8'

services:
  biometria_py:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biometria_py
    ports:
      - "8085:5000"
    restart: always
    environment:
      - DEEPFACE_HOME=/app
      - DB_SERVER=190.85.54.78
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=ADMadm1234
      - DB_DATABASE=ARTDECON
    volumes:
      - biometria_temp_faces:/app/temp_faces
      - ./fotos_empleados:/app/fotos_empleados

volumes:
  biometria_temp_faces:
